version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: hookbuilder-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=hookbuilder2025
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Warsaw
      - N8N_LOG_LEVEL=debug
    volumes:
      - ./apps/n8n/data:/home/node/.n8n
      - ./apps/n8n/nodes:/home/node/.n8n/custom
    restart: unless-stopped
    networks:
      - hookbuilder

  # Database for n8n (optional but recommended for production)
  postgres:
    image: postgres:15
    container_name: hookbuilder-postgres
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hookbuilder
    restart: unless-stopped

networks:
  hookbuilder:
    driver: bridge

volumes:
  postgres_data: